### ISSUE TITLE
Please provide the remote address to the pam stack

### ISSUE THREAD

**Issue by dorchain** [processone/epam#2] opened 2015-02-26 17:44 UTC
Specifically, please  forward the remote address of the user trying to authenticate in the PAM_RHOST item to the pam stack (currently, PAM_SERVICE and PAM_USER are supplied) That would allow to thread users diffrently depending where they come from (e.g. two-factor auth in general, single factor from well-known places)

**Comment by jeffWelling** [comment] 2015-03-29 17:34
Hello and thank you for reporting this bug!

After some investigation it looks like this is actually a communications issue resulting from the log message that's emitted when one authenticates through epam. 

RHOST is set only after a successful login, so in the log message we see that rhost is blank, but if you setup pam_access.so and access.conf to reject all network logins, in my tests this is enforced.
We can see the code in this file around line 72: https://github.com/processone/epam/blame/master/c_src/epam.c#L72 
It seems this code was commited quite a ways back, which is why I believe this is simply a comms issue based on that log confusing log message.

I admit, there may be room for improvement in that if RHOST was set earlier then the log message would be accurate, but I'm not familiar enough with PAM to know what best practice is, and this solution *is* functional.

If you have some time, can you please confirm if this is in fact broken on your system? If so, please report back as much information as you can about your distribution and the verison of the relevant packages. Thanks!

**Comment by jeffWelling** [comment] 2015-03-29 18:04
Thinking about this further, I think it would be best to leave this bug open until the code can be corrected to set RHOST earlier in the process so that the log message is accurate. 

People depend on the logs to be accurate and to contain all relevant information, if these log messages are not accurate I think they should be corrected.

**Comment by jeffWelling** [comment] 2015-03-29 18:31
Deleted my previous comments because I was wrong. I was confusing RUSER with RHOST.

However, confusingly, my tests are showing that IP restrictions applied through pam_access.so and access.conf do in fact block based on IP, but after carefully reviewing the code, RHOST isn't actually being set anywhere, so I'm rather confused about how that blocking is occurring.

**Comment by jeffWelling** [comment] 2015-03-29 19:22
I did some more testing, I think the problem is that when RHOST is not set, you can't accept or block *hostnames specifically* in access.conf. I was confused by the wording of the ticket.
My tests were done using IP networks in access.conf, and it appears that works regardless of whether or not RHOST is set.

**Comment by dorchain** [comment] 2015-03-30 07:59
On Sun, Mar 29, 2015 at 12:22:01PM -0700, Jeff Welling wrote:
> 
> I did some more testing, I think the problem is that when RHOST is not set,
> you can't accept or block *hostnames specifically* in access.conf. I was
> confused by the wording of the ticket.
> My tests were done using IP networks in access.conf, and it appears that
> works regardless of whether or not RHOST is set.

epam.c does not set the PAM_RHOSTS item, thus there is no way of
knowing for the pam stack where is user is coming from.

See also http://linux.die.net/man/3/pam_get_item:
PAM_RHOST
    The requesting hostname (the hostname of the machine from
    which the PAM_RUSER entity is requesting service). That is
    PAM_RUSER@PAM_RHOST does identify the requesting user. In
    some applications, PAM_RHOST may be NULL. In such situations,
    it is unclear where the authentication request is originating
    from. 

pam_access specially assumes a local service when RHOSTS ist
empty or not set. If it is set, it performs a forward and reverse
lookup on the value, which allows access control on fdqn and
IP address.

This is exactly what I want.

**Comment by jeffWelling** [comment] 2015-03-30 16:05
I don't dispute that epam is not currently setting RHOSTS but I'm confused about how my tests with IP ranges succeeded in light of that. 

Regardless, as a weekend exercise I've crafted a patch which I think allows setting RHOST in epam, I'm just trying to test it on my local system before submitting a pull request.

**Comment by dorchain** [comment] 2015-03-30 16:44
On Mon, Mar 30, 2015 at 09:05:29AM -0700, Jeff Welling wrote:
> Regardless, as a weekend exercise I've crafted a patch which I think allows
> setting RHOST in epam, I'm just trying to test it on my local system before
> submitting a pull request. 

Thanks!
Well, when you are pleased with alpha testing I can do beta ;-)

**Comment by jeffWelling** [comment] 2015-04-01 05:24
In my tests, the patch does allow epam to pass a value to PAM_RHOSTS. But I have a curious problem.  I thought all I would have to do is compile it, replace the original binary, and test it, but I had to add the binary to a second location as well.

The original binary, on my Debian system, is at /usr/lib/erlang/p1_pam/bin/epam. I put my copy of epam there and tried to restart ejabberd but found ejabberd was looking for epam in an additional location: /usr/lib/erlang/p1_pam/bin/epam

I'm trying to figure out this oddity before submitting my pull request, but my current code is up in my repo, please feel free to take a look and give it a try: https://github.com/jeffWelling/epam/tree/add_rhost

**Comment by jeffWelling** [comment] 2015-04-01 05:28
To clarify, I'm testing PAM_RHOST support in epam with ejabberd.

**Comment by jeffWelling** [comment] 2015-04-01 05:50
Aha! The oddity is caused by a change that the Debian erlang-p1-pam package maintainers made.

**Comment by dorchain** [comment] 2015-04-01 06:22
On Tue, Mar 31, 2015 at 10:50:17PM -0700, Jeff Welling wrote:
> 
> Aha! The oddity is caused by a change that the Debian erlang-p1-pam package
> maintainers made.

I have a debian bug report open for this. Meanwhile, my
workaround is:
$ ls -l /usr/lib/erlang/p1_pam/bin/epam /usr/lib/x86_64-linux-gnu/ejabberd/priv/bin/epam
-rwxr-sr-x 1 root shadow 55176 Oct  1 14:49 /usr/lib/erlang/p1_pam/bin/epam
 lrwxrwxrwx 1 root root      31 Oct 16 10:46 /usr/lib/x86_64-linux-gnu/ejabberd/priv/bin/epam -> /usr/lib/erlang/p1_pam/bin/epam

**Comment by jeffWelling** [comment] 2017-03-07 05:52
I failed to correctly reference this Issue from my commit message but now that the PR is merged, this issue can be resolved.

**Closed** 2017-03-07 07:52 UTC
